FROM logstash:8.5.0

COPY logstash.conf /usr/share/logstash/pipeline/logstash.conf
COPY logstash.conf /usr/share/logstash/config/logstash.conf
COPY logstash.yml /usr/share/logstash/config/logstash.yml